export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SITE_URL = "http://localhost:8088"
// export const SITE_URL = "http://66.235.194.119:8088"

export const GET_CONCESSION_LIST_SUCCESS = "GET_CONCESSION_LIST_SUCCESS"
export const ADD_CONCESSION_SUCCESS = "ADD_CONCESSION_SUCCESS"
export const EDIT_CONCESSION_SUCCESS = "ADD_CONCESSION_SUCCESS"
export const DELETE_CONCESSION_SUCCESS = "DELETE_CONCESSION_SUCCESS"
export const CONCESSION_TASK_FAIL = "CONCESSION_TASK_FAIL"

export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const EDIT_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const CATEGORY_TASK_FAIL = "CATEGORY_TASK_FAIL"

export const GET_SUBJECT_LIST_SUCCESS = "GET_SUBJECT_LIST_SUCCESS"
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS"
export const EDIT_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS"
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS"
export const SUBJECT_TASK_FAIL = "SUBJECT_TASK_FAIL"

export const GET_HOLIDAY_LIST_SUCCESS = "GET_HOLIDAY_LIST_SUCCESS"
export const ADD_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS"
export const EDIT_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS"
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS"
export const HOLIDAY_TASK_FAIL = "HOLIDAY_TASK_FAIL"

export const GET_CLASSINFO_LIST_SUCCESS = "GET_CLASSINFO_LIST_SUCCESS"
export const ADD_CLASSINFO_SUCCESS = "ADD_CLASSINFO_SUCCESS"
export const EDIT_CLASSINFO_SUCCESS = "ADD_CLASSINFO_SUCCESS"
export const DELETE_CLASSINFO_SUCCESS = "DELETE_CLASSINFO_SUCCESS"
export const CLASSINFO_TASK_FAIL = "CLASSINFO_TASK_FAIL"




export const ERASED = "ERASED"